name: Build
on:
  push:
    paths:
    - 'src/**/*.{ts,tsx}'
    - '.github/workflows/**'
    - 'public/**'
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install --frozen-lockfile
    - run: npm run build
